version: "3.8"
services:
  db:
    container_name: db
    build: ./api
    restart: on-failure
    ports:
      - 3002:3002
    networks:
      - lol   
  api:
    container_name: api
    build: ./API
    restart: on-failure
    ports:
      - 3001:3001
    networks:
      - lol   
  react:
    container_name: react
    build: ./REACT/
    restart: on-failure
    ports:
      - 8000:3000
    networks:
      - lol  
networks:
  lol:
    name: lol
    external: true
